"""changed the name of the foreign key

Revision ID: 741ad4d90471
Revises: d43be984002e
Create Date: 2020-07-17 12:36:08.785896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741ad4d90471'
down_revision = 'd43be984002e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('churchService', sa.Column('church_id', sa.Integer(), nullable=False))
    op.drop_constraint('churchService_church_fkey', 'churchService', type_='foreignkey')
    op.create_foreign_key(None, 'churchService', 'church', ['church_id'], ['id'])
    op.drop_column('churchService', 'church')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('churchService', sa.Column('church', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'churchService', type_='foreignkey')
    op.create_foreign_key('churchService_church_fkey', 'churchService', 'church', ['church'], ['id'])
    op.drop_column('churchService', 'church_id')
    # ### end Alembic commands ###
