"""empty message

Revision ID: 901cf3b062b4
Revises: 741ad4d90471
Create Date: 2020-07-17 12:40:34.584488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901cf3b062b4'
down_revision = '741ad4d90471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('churchService', 'church_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('churchService', 'church_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
