"""added church service table

Revision ID: d1241794280a
Revises: d23bba661d00
Create Date: 2020-07-17 11:22:07.316407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1241794280a'
down_revision = 'd23bba661d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churchService',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('number_of_attendees', sa.Integer(), nullable=True),
    sa.Column('church', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['church'], ['church.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('churchService')
    # ### end Alembic commands ###
