"""added table for attendees

Revision ID: d43be984002e
Revises: ef8f2a74851b
Create Date: 2020-07-17 11:33:50.581105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43be984002e'
down_revision = 'ef8f2a74851b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('area', sa.String(length=30), nullable=False),
    sa.Column('service', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service'], ['churchService.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendees')
    # ### end Alembic commands ###
