"""changed tablename

Revision ID: d496bdfafd74
Revises: 901cf3b062b4
Create Date: 2020-07-17 12:48:01.175254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd496bdfafd74'
down_revision = '901cf3b062b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serviceattendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('area', sa.String(length=30), nullable=False),
    sa.Column('service', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service'], ['churchService.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('attendees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('area', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('service', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service'], ['churchService.id'], name='attendees_service_fkey'),
    sa.PrimaryKeyConstraint('id', name='attendees_pkey')
    )
    op.drop_table('serviceattendees')
    # ### end Alembic commands ###
