"""added capacity column to service table

Revision ID: ef8f2a74851b
Revises: d1241794280a
Create Date: 2020-07-17 11:27:02.141244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8f2a74851b'
down_revision = 'd1241794280a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('churchService', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('churchService', 'capacity')
    # ### end Alembic commands ###
